cvmfs/doc-cvmfs

- figures/tabserverparameters.tex
Quite a few server configuration parameters needed to be added to the documentation:
```
CVMFS_INCLUDE_XATTRS
CVMFS_STRATUM1
CVMFS_AUTO_REPAIR_MOUNTPOINT
CVMFS_UNION_FS_TYPE
CVMFS_AUFS_WARNING
CVMFS_HASH_ALGORITHM
CVMFS_CATALOG_ENTRY_WARN_THRESHOLD
CVMFS_NUM_WORKERS
CVMFS_PUBLIC_KEY
CVMFS_AUTO_TAG
CVMFS_GARBAGE_COLLECTION
```
> Add New Server Parameters

- cpt-repo.tex
> FIX: Bucket Name of Single S3 Bucket

- cpt-servermeta.rst
typo fixes, jq dependency info
> minor text edits

- cpt-releasenotes.rst
removed GDB testing disclaimer
> release note edit: testing disclaimer

- cpt-gateway-services.rst
- index.rst
Addresses [CVM-1303](https://sft.its.cern.ch/jira/browse/CVM-1303).
Provides configuration instructions for a release manager machine.
> Adding some documentation for gateway and release manager configuration

- cpt-repo.rst
For changes in [CVM-1095](https://sft.its.cern.ch/jira/browse/CVM-1095)
> add info regarding cvmfs_server gc -a

- apx-parameters.rst
- apx-serverinfra.rst
- cpt-repo.rst
Changes corresponding to [CVM-1186](https://sft.its.cern.ch/jira/browse/CVM-1186)
> add that overlayfs on RHEL7.3 or later supports ext3 for spool

- cpt-configure.rst
- cpt-details.rst
Changes corresponding to [CVM-992](https://sft.its.cern.ch/jira/browse/CVM-992)
> add info about additional blacklist format

- apx-security.rst
- cpt-repo.rst
Corresponding to [CVM-1259](https://sft.its.cern.ch/jira/browse/CVM-1259)
> add section on master keys, masterkeycard

- cpt-releasenotes.rst
Please merge in master and 2.4 branches
> small updates to the 2.4 release notes

- cpt-large-scale.rst
- cpt-repo.rst
- index.rst
Not entirely complete, but I wanted to make sure the approach is reasonable and what upstream would like.
> Initial attempt at the description of large CVMFS repositories.

- cpt-replica.rst
In response to questions on cvmfs-talk.
> improve description of stratum 1 squid

- cpt-details.rst
Replaced note about X-CVMFS2 with User-Agent.
Fix few typos and links.
I wasn't sure of what to add at https://github.com/cvmfs/doc-cvmfs/pull/76/files?diff=split#diff-89bae9675dd4d1cae5ddfd3ddd794bc6L775.
> Updates to Implementation Notes

- cpt-servermeta.rst
This sentence doesn't parse correctly. Presumably this interpretation of it is correct?
> fix sentence structure

- cpt-repository-gateway.rst
Update the GW instructions after the resolution of [CVM-1557](https://sft.its.cern.ch/jira/browse/CVM-1557).
This includes the changes proposed in #86
> Update gateway instructions

- apx-parameters.rst
- Added description for  `CVMFS_EXTENDED_GC_STATS`, `CVMFS_PRINT_STATISTICS`, `CVMFS_STATISTICS_DB`
> Add documentation for gathering statistics feature.

- cpt-details.rst
Added description for the SQLite database file that stores the statistics.
> Added statistics database schema description

- cpt-repo.rst
Related to [CVM-1641](https://sft.its.cern.ch/jira/browse/CVM-1641).
> S3 config: document CVMFS_S3_DNS_BUCKETS parameter

- cpt-details.rst
Details described in individual commits.
> minor fixes

- cpt-shrinkwrap.rst
- part-advanced.rst
This is a first attempt at documenting the usage of CVMFS Shrinkwrap for the read-the-docs.
Possible additions to this pull request or future ones.
- Explain commandline options
- Explain Statistics produced
- Explicit container instructions
- Docker injection instructions
> Shrinkwrap tutorial

- cpt-releasenotes.rst
> minor language fixes

- cpt-quickstart.rst
> Modified quickstart for LHC@home

- cpt-repository-gateway.rst
Explain all 3 keys are required, and what each one is.
Fix some markup rendering.
Minor language issues and clarifications
e.g. "intermediate" is not a verb, but "mediate" is.
> clarify keys required, fix spelling, typos etc

- cpt-ducc.rst
- cpt-repo.rst
- part-advanced.rst
Add small documentation for the ingest command.
> add documentation for ingest command

- cpt-ducc.rst
> fix typos, spelling etc

- cpt-repo.rst
Was not clear what "degenerated" meant in this context.
Can use dirtab and manually placed catalog files together.
> change wording and add note on dirtab

- cpt-ducc.rst
basic requirements description
> add requirements

- apx-parameters.rst
- cpt-replica.rst
See [CVM-1779](https://sft.its.cern.ch/jira/browse/CVM-1779)
> Add snapshot group

- cpt-replica.rst
Fix formatting mistakes from pr #130
> Fix formatting in the new geo setup API section

- apx-parameters.rst
Following on to #130 and #131.
> Add CVMFS_GEO parameters

- cpt-containers.rst
- index.rst
Add documentation about use of containers with cvmfs and unpacked.
> add containers use documentation

- cpt-containers.rst
> Fix typos & make various improvements in the new cpt-containers page

- cpt-containers.rst
I was re-reading and @jblomer merged the last one a little too fast, before I had a chance to update the last PR.
> A couple of more wording improvements for cpt-containers

- apx-parameters.rst
- cpt-repo.rst
Goes with:
https://github.com/cvmfs/cvmfs/pull/2588
> document flags used for the https implementation

- cpt-releasenotes.rst
Also put in a link to Dockerhub , which I'm only guessing is the correct one..
> fix formatting and spelling of daemonset

- cpt-replica.rst
- cpt-squid.rst
Prompted by discussions with @jblomer @rptaylor @dvandok @bedroge and @boegel
> Improve squid advice and mention high availability
