cvmfs/doc-cvmfs

- apx-serverinfra.tex
- cpt-repo.tex
- cvmfstech.tex
- figures/tablocalstorageanatomy.tex
- figures/tabparameters.tex
- figures/tabrepoconfiganatomy.tex
- figures/tabrepospoolanatomy.tex
- figures/tabserveranatomy.tex
- figures/tabserverparameters.tex
This is a (admittedly rough) description of the entire CernVM-FS Server infrastructure and all of its constituents. I believe it serves more as an overview but I hope it will help @traylenator to setup a server without using `cvmfs_server`.
> Description of CVMFS Server Infrastructure

- apx-parameters.rst
- apx-references.rst
- apx-rpms.rst
- apx-serverinfra.rst
- cpt-configure.rst
- cpt-details.rst
- cpt-overview.rst
- cpt-quickstart.rst
- cpt-replica.rst
- cpt-repo.rst
- cpt-squid.rst
- index.rst
This moves the references away from each individual page and creates a dedicated subsection for them. Furthermore it rewires the citations in the text to link to this central references page.
Note: This patch set is almost certainly incompatible with #37 -- I will rebase the documentation updates shortly.
> FIX: References

- apx-parameters.rst
- apx-references.rst
- apx-rpms.rst
- apx-serverinfra.rst
- cpt-configure.rst
- cpt-details.rst
- cpt-overview.rst
- cpt-quickstart.rst
- cpt-replica.rst
- cpt-repo.rst
- cpt-squid.rst
- index.rst
This is a back-port of the [reference and citation updates](https://github.com/cvmfs/doc-cvmfs/pull/38) on master. Git is pure magic!
> FIX: 2.1.20 References

- apx-parameters.rst
- apx-references.rst
- apx-rpms.rst
- apx-serverinfra.rst
- cpt-configure.rst
- cpt-details.rst
- cpt-overview.rst
- cpt-quickstart.rst
- cpt-replica.rst
- cpt-repo.rst
- cpt-squid.rst
This replaces several unicode characters by its ASCII friends. Note that rST is actually unicode aware and is meant to use unicode characters instead of clumsy escape sequences. What I replaced are characters that are not easily distinguishable (writable) in a plain-text editor - see below.
For other characters (for example René - the accent aigu) stays unicode.
In detail:
* 0x00A0 (non breaking space) replaced by standard space
* 0x2013 (En dash – ) by standard -
* 0x2019 (Right single quote ’ ) by standard '
* 0x2026 (horizontal ellipsis … ) by three dots ...
* 0x201C/0x201D (left/right double quotes “ ” ) by "
> FIX: Replace Certain Unicode Characters by ASCII

- cpt-repo.rst
This should go in as soon as [Feature: `cvmfs_server mount [-a]`](https://github.com/cvmfs/cvmfs/pull/1551) get merged and released.
> Add Documentation for `cvmfs server mount`

- cpt-repo.rst
This adds a subsection in the repository creation and updating section on how to create variant symlinks and set defaults.
> Improve documentation on variant symlinks

- cpt-hpc.rst
changes "-DCVMFS_PRELOADER=on" to "-DBUILD_PRELOADER=on".
> fix for the cmake option used to install cvmfs_preloader

- cpt-details.rst
Corresponding to change in [CVM-1336](https://sft.its.cern.ch/jira/browse/CVM-1336)
> change default catalog TTL from 15 to 4 minutes

- apx-serverinfra.rst
Ran across someone who read this bullet point and thought all clients
needed a custom kernel to use CVMFS.
> Clarify the explanation of the kernel version needed.

- cpt-quickstart.rst
This issue was already fixed in CVMFS v2.3.5 so a manual step is not needed. Trying to minimize the number of redundant configuration steps needed.
> remove old workaround for autofs bug

- cpt-repo.rst
I think a gc included with a build script may be more practical for publishing than a system-wide cron, because otherwise it will be hard to get the timing right to make sure they never happen at the same time (especially on a multi-tenant release manager machine).
> give alternate way to do gc

- cpt-gateway-services.rst
Covers changes introduced in CVMFS and CVMFS Repository Services ([CVM-1444](https://sft.its.cern.ch/jira/browse/CVM-1444) and [CVM-1445](https://sft.its.cern.ch/jira/browse/CVM-1445)).
> Updating repository gateway documentation

- cpt-gateway-services.rst
Mostly corrections for English.  Also removed "dedicated" from release manager description, because I think this feature is likely to result in release manager tasks being done on machines that have additional purposes for the VOs, at least in the Fermilab environment.
I was surprised to read that the gateway software is distributed as a tarball.  I hope that is planned to be changed to become available in the native packaging.
> minor wording changes to the gateway documentation

- cpt-replica.rst
```
$ rpm -qp --scripts cvmfs-server-2.4.4-1.el6.x86_64.rpm | grep semanage
$ rpm -qp --scripts cvmfs-server-2.4.4-1.el7.centos.x86_64.rpm | grep semanage
/usr/sbin/semanage port -m -t http_port_t -p tcp 8000 2>/dev/null || :
```
> Only the EL7 (not EL6) cvmfs-server RPM does this

- cpt-quickstart.rst
Previously unclear what to include in the config file if no proxies were required. Information was there for Mac OSX instructions but not Linux
>  Clarify proxy settings if no proxy needed/unsure 

- cpt-releasenotes.rst
The documentation  implied that a server migrate is not required for stratum 1.
According to my testing this is incorrect:
Please run `cvmfs_server migrate` to update your repository before proceeding.
ERROR from cvmfs_server snapshot!
> do server migrate for both stratum 0 and 1

- cpt-graphdriver.rst
I am upgrading the documentation for docker2cvmfs introducing the new subcommand make-thin
The interface of the command is quite narrow and I believe to have provide enough information to cover every single parameter.
Before to merge I have to understand how to distribute the executable and so provide a download link.
> Upgrade doc for docker2cvmfs

- apx-parameters.rst
Based on context (what snapshot -a does) this seems to make more sense.
> CVMFS_REPLICA_ACTIVE should apply to repository?

- cpt-squid.rst
Incl. minor language smoothing
Also @DrDaveD I noticed the squid ACLs don't seem fully up to date.
The following is from the latest frontier-squid:
```
acl MAJOR_CVMFS dstdom_regex ^((cvmfs-stratum-.*|hepvm)\.cern\.ch|(cernvmfs|cvmfs).*\.gridpp\.rl\.ac\.uk|cvmfs.*\.racf\.bnl\.gov|cvmfs.*\.fnal\.gov|klei\.nikhef\.nl|cvmfs.*\.grid\.sinica\.edu\.tw|cvmfs.*\.lcg\.triumf\.ca|(cvmfs-s1|oasis).*\.opensciencegrid\.org|cvmfs.*\.ihep\.ac\.cn|hcc-cvmfs\.unl\.edu|.*cvmfs\.openhtc\.io)$
```
Should that be used in the documentation instead?
> fix some typos

- cpt-configure.rst
This formatting should render the links to other sections correctly.
Also remove unnecessary quotation marks around "config repository", since that is the actual name of it.
> fix broken links

- cpt-repository-gateway.rst
Shuffle a few paragraphs so that the content flows in a more logical order, from one config file to the other config file to lastly starting the application.
All the config settings are described together in the same list.
Also based on my observations, a gateway restart is required if an API key changes, so this is mentioned too.
> rearrange documentation info

- cpt-ducc.rst
The name of the executable installed by the cvmfs-ducc-2.6.0-1.el7.x86_64 is /usr/bin/cvmfs_ducc
> executable name is cvmfs_ducc

- cpt-configure.rst
Adjust wording, add some clarifications, use more natural language. This should make it easier for regular users (who are not administrators but need to figure out what to do regarding proxies if they are setting up CVMFS on their own system) to understand.
> revisions to CVMFS_HTTP_PROXY documentation

- cpt-configure.rst
This will give users and admins an idea of some of the considerations and reasoning involved in constructing a suitable proxy list, as well as examples of valid syntax.
> add some basic examples of CVMFS_HTTP_PROXY

- cpt-repo.rst
In addition to this change, the 'data files' section seems to have some sentences with missing parts:
> In general, a good rule of thumb is to calculate the maximum rate at which jobs typically start and
> limit the amount of data that might be read from a web proxy to (???) per thousand jobs, 
> assuming a reasonable amount of overlap of jobs onto the same worker nodes. Also, limit the 
> amount of data that will be put into any one worker node cache to (???). 
@DrDaveD any idea what happened there or what it's supposed to say?
https://cvmfs.readthedocs.io/en/latest/cpt-repo.html#data-files
> refer to alien cache for large data files

- cpt-configure.rst
Somebody who is setting up a cvmfs NFS server gave me this hint.  Without doing this, `/cvmfs/config-osg.opensciencegrid.org` at boot time often had an error showing as
```
$ ls -la /cvmfs
ls: cannot access /cvmfs/config-osg.opensciencegrid.org: No such file or directory
total 0
drwxr-xr-x  12 root  root  287 Feb  4 09:44 .
dr-xr-xr-x. 18 root  root  275 Feb  4 09:54 ..
drwxr-xr-x   2 cvmfs cvmfs   6 Feb  4 09:43 atlas.cern.ch
drwxr-xr-x   2 cvmfs cvmfs   6 Feb  4 09:43 cms.cern.ch
d??????????  ? ?     ?       ?            ? config-osg.opensciencegrid.org
```
> Add hint for ordering mounts at boot with config repo

- cpt-configure.rst
This should say
```
In the NFS mode, upon mount an additional directory nfs_maps.$repository_name appears in the CernVM-FS cache directory.
```
Instead of
```
In the NFS mode, upon mount an additionally directory nfs_maps.$repository_name appears in the CernVM-FS cache directory.
```
> Fix typo in the NFS Mode section of CVMFS Client Configuration Doc

- cpt-details.rst
I found that the "rawlink" attribute required the attr -R option to read it.  It also requires running as root on EL6, but it does not on EL7.  Given the limited lifetime left to EL6 I don't think it's worth mentioning that requirement.
> Clarify how to access the rawlink attribute

- cpt-replica.rst
Discussed in [CVM-1880](https://sft.its.cern.ch/jira/browse/CVM-1880).
> Call /usr/share/GeoIP a default directory instead of default path

- cpt-plugins.rst
As the code specifies in:
https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/authz/authz_fetch.cc#L259
> Fix helper name in search path

- cpt-hpc.rst
Added links to unprivileged cvmfs and to cvmfs_shrinkwrap while adding judgements on each of the various methods to provide advice.
This was prompted by an OSG user who, after reading that documentation page, thought that cvmfs_preload was his best option for getting a cvmfs repository on an HPC that could not install a cvmfs client.
> Update advice on running on HPC systems

- apx-security.rst
- cpt-configure.rst
- cpt-hpc.rst
Fixes wrong hyperlink syntax added in #152.
Also moves remaining text about running without a local native cvmfs client up to be with the rest.
If it looks good, please also merge into stable branch.
> Correct hpc link syntax, and other HPC doc cleanups

- cpt-hpc.rst
> Correct typo in reference to loopback filesystems
